---
# tasks file for jenkins
- name: Add terraform key
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present

- name: Add Terraform repository
  apt_repository:
    repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main'
    state: present

- name: Install Terraform binary package
  apt:
    name: "terraform"
    update_cache: true

- name: Jenkins is started
  service:
    name: terraform
    state: started
